---
#--------------------------------------------------------------------
# Each cluster provisioned must have an entry in the 'clusters'
# dictionary.  The cluster name is the key under 'clusters'
# and will be used to determine the name of various resources to
# be provisioned (e.g. aggrs).  Therefore the name used for the
# cluster MUST be a legal name for all resources types (e.g.
# no hyphens in the name because hyphens are illegal characters for
# aggr names).  The cluster name does not need to be DNS
# resolvable because the 'mgmt_ip' is always used to communicate with
# the cluster.
#--------------------------------------------------------------------
clusters:
  cluster1:
    mgmt_ip:          '192.168.61.50'
    username:         "{{ vault['clusters']['Cluster1']['username'] }}"
    password:         "{{ vault['clusters']['Cluster1']['password'] }}"
  # XRDCNLSHRC02:
  #   mgmt_ip:          '10.28.184.14'
  #   username:         "{{ vault['clusters']['XRDCNLSHRC02']['username'] }}"
  #   password:         "{{ vault['clusters']['XRDCNLSHRC02']['password'] }}"
  # Cluster02:
  #  mgmt_ip:          '10.242.1.10'
  #  username:         "{{ vault['clusters']['Cluster01']['username'] }}"
  #  password:         "{{ vault['clusters']['Cluster01']['password'] }}"
  # PZDCNLSHRC03:
  #   mgmt_ip:          '10.242.1.10'
  #   username:         "{{ vault['clusters']['PZDCNLSHRC03']['username'] }}"
  #   password:         "{{ vault['clusters']['PZDCNLSHRC03']['password'] }}"
  
