---

-  name: "BLOCKnRESCUE: ONTAP_CIFS"
   block:
      -  set_fact:
            service_start_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"

      -  name: "execute volume provision"
         netapp.ontap.na_ontap_cifs:
            hostname:                  "{{ clusters[loop_arg['hostname']]['mgmt_ip'] }}"
            username:                  "{{ clusters[loop_arg['hostname']]['username'] }}"
            password:                  "{{ clusters[loop_arg['hostname']]['password'] }}"
            
            cert_filepath:             "{{ loop_arg['cert_filepath']                | default(omit) }}"
            feature_flags:             "{{ loop_arg['feature_flags']                | default(omit) }}"
            http_port:                 "{{ loop_arg['http_port']                    | default(omit) }}"
            https:                     "{{ loop_arg['https']                        | default('true') }}"
            key_filepath:              "{{ loop_arg['key_filepath']                 | default(omit) }}"
            ontapi:                    "{{ loop_arg['ontapi']                       | default(omit) }}"
            use_rest:                  "{{ loop_arg['use_rest']                     | default(omit) }}"
            validate_certs:            "{{ loop_arg['validate_certs']               | default('false') }}"

            share_name:                "{{ loop_arg['share_name'] }}"
            vserver:                   "{{ loop_arg['vserver'] }}"
            http_port:                 "{{ loop_arg['http_port']                    | default('443') }}"         
            path:                      "{{ loop_arg['path']                         | default(omit) }}"
            share_properties:          "{{ loop_arg['share_properties']             | default(omit) }}"  
            state:                     "{{ loop_arg['state']                        | default(omit) }}"
            symlink_properties:        "{{ loop_arg['symlink_properties']           | default(omit) }}"  
            use_rest:                  "{{ loop_arg['use_rest']                     | default(omit) }}"
            vscan_fileop_profile:      "{{ loop_arg['vscan_fileop_profile']         | default(omit) }}"  

         loop:    "{{ args }}"
         loop_control:
            loop_var:   loop_arg
         register:      role_result

   rescue:
      -  name: Set Play Status
         set_fact:
            playbook_status:   "failed"

   always:
      -  name: add log msg
         vars:
            role_log:
               role: "ONTAP_CIFS"
               timestamp:
                  start_time: "{{service_start_time}}"
                  end_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
               service_status: "{{ playbook_status }}"
               result: "{{role_result}}"   
         set_fact:
            global_log_msgs:   "{{ global_log_msgs + [ role_log ] }}"