---

-  name: "BLOCKnRESCUE: ONTAP_NET_PORT"
   block:
      -  set_fact:
            service_start_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"

      -  name: 'configure network port'
         netapp.ontap.na_ontap_net_port:
            hostname:            "{{ clusters[loop_arg['hostname']]['mgmt_ip'] }}"
            username:            "{{ clusters[loop_arg['hostname']]['username'] }}"
            password:            "{{ clusters[loop_arg['hostname']]['password'] }}"

            cert_filepath:       "{{ loop_arg['cert_filepath']                | default(omit) }}"
            feature_flags:       "{{ loop_arg['feature_flags']                | default(omit) }}"
            http_port:           "{{ loop_arg['http_port']                    | default(omit) }}"
            https:               "{{ loop_arg['https']                        | default('true') }}"
            key_filepath:        "{{ loop_arg['key_filepath']                 | default(omit) }}"
            ontapi:              "{{ loop_arg['ontapi']                       | default(omit) }}"
            use_rest:            "{{ loop_arg['use_rest']                     | default(omit) }}"
            validate_certs:      "{{ loop_arg['validate_certs']               | default('false') }}"

            node:                "{{ loop_arg['node'] }}"
            ports:               "{{ loop_arg['ports']  }}"
            state:               "{{ loop_arg['state']                        | default('present') }}"
            autonegotiate_admin: "{{ loop_arg['autonegotiate_admin']          | default(omit) }}"
            duplex_admin:        "{{ loop_arg['duplex_admin']                 | default(omit)}}"
            flowcontrol_admin:   "{{ loop_arg['flowcontrol_admin']            | default(omit) }}"
            ipspace:             "{{ loop_arg['ipspace']                      | default(omit) }}"
            mtu:                 "{{ loop_arg['mtu']                          | default(omit) }}"
            speed_admin:         "{{ loop_arg['speed_admin']                  | default(omit) }}"

         loop: "{{ args }}"
         loop_control:
            loop_var:      loop_arg
         register:   role_result

   rescue:
      -  name: Set Play Status
         set_fact:
            playbook_status:   "failed"

   always:
      -  name: add log msg
         vars:
            role_log:
               role: "ONTAP_NET_PORT"
               timestamp:
                  start_time: "{{service_start_time}}"
                  end_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
               service_status: "{{ playbook_status }}"
               result: "{{role_result}}"   
         set_fact:
            global_log_msgs:   "{{ global_log_msgs + [ role_log ] }}"