---

-  name: "BLOCKnRESCUE: ONTAP_NET_SUBNET"
   block:
      -  set_fact:
            service_start_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
            
      -  name: 'configure network subnet'
         netapp.ontap.na_ontap_net_subnet:
            hostname:            "{{ clusters[loop_arg['hostname']]['mgmt_ip'] }}"
            username:            "{{ clusters[loop_arg['hostname']]['username'] }}"
            password:            "{{ clusters[loop_arg['hostname']]['password'] }}"

            cert_filepath:       "{{ loop_arg['cert_filepath']                | default(omit) }}"
            feature_flags:       "{{ loop_arg['feature_flags']                | default(omit) }}"
            http_port:           "{{ loop_arg['http_port']                    | default(omit) }}"
            https:               "{{ loop_arg['https']                        | default('true') }}"
            key_filepath:        "{{ loop_arg['key_filepath']                 | default(omit) }}"
            ontapi:              "{{ loop_arg['ontapi']                       | default(omit) }}"
            use_rest:            "{{ loop_arg['use_rest']                     | default(omit) }}"
            validate_certs:      "{{ loop_arg['validate_certs']               | default('false') }}"

            name:                "{{ loop_arg['name'] }}"
            subnet:              "{{ loop_arg['subnet'] }}"
            broadcast_domain:    "{{ loop_arg['broadcast_domain'] }}"
            state:               "{{ loop_arg['state']                        | default('present') }}"
            from_name:           "{{ loop_arg['from_name']                    | default(omit) }}"
            gateway:             "{{ loop_arg['gateway']                      | default(omit)}}"
            ip_ranges:           "{{ loop_arg['ip_ranges']                    | default(omit) }}"
            ipspace:             "{{ loop_arg['ipspace']                      | default(omit) }}"

         loop: "{{ args }}"
         loop_control:
            loop_var:      loop_arg
         register:   role_result

   rescue:
      -  name: Set Play Status
         set_fact:
            playbook_status:   "failed"

   always:
      -  name: add log msg
         vars:
            role_log:
               role: "ONTAP_NET_SUBNET"
               timestamp:
                  start_time: "{{service_start_time}}"
                  end_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
               service_status: "{{ playbook_status }}"
               result: "{{role_result}}"   
         set_fact:
            global_log_msgs:   "{{ global_log_msgs + [ role_log ] }}" 