---

- set_fact:
      service_start_time: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- name: "BLOCKnRESCUE: VOLUME_RESIZE"
  block:  
      - name: "Run volume_resize"
        vars:
          #files_used_pct: "{{ ( 100 * loop_arg['files_used'] | int / loop_arg['files_total'] | int ) | round }}"
          #desired_volume_size: "{{ ( loop_arg['size'] | int * 100 / volume_pct_target ) | int ) | round }}"
          desired_volume_size: "{{ ( loop_arg['size'] * volume_pct_target )}} GB"
          #desired_volume_size: "{{loop_arg['size']}}"  
        na_ontap_command:
          hostname: "{{ clusters[loop_arg['hostname']]['mgmt_ip'] }}"
          username: "{{ clusters[loop_arg['hostname']]['username'] }}"
          password: "{{ clusters[loop_arg['hostname']]['password'] }}"
          https:            true  
          validate_certs:   false 
          command: [ 'volume', 'size', '-vserver', '{{ loop_arg["vserver"] }}', '-volume', '{{ loop_arg["volume"] }}', '-new-size', '{{desired_volume_size}}' ]
        
        loop: "{{ args }}"
        loop_control:
          loop_var: loop_arg
        register: role_result
    
  rescue:
      - name: 'Global playbook logging'
        include_role: 
            name: "log/global_logr"       

        vars:
            role_log:
              role: "VOLUME_RESIZE"
              timestamp:
                  start_time: "{{service_start_time}}"
                  end_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
              service_status: "failed"
              result: "{{role_result}}"  
            global_log:  "{{ global_log_msgs + [ role_log ] }}" 

      - name: "STop the Play"
        meta: end_play   

-  name: add log msg
   vars:
      role_log:
         role: "VOLUME_RESIZE"
         timestamp:
            start_time: "{{service_start_time}}"
            end_time: "{{ lookup('pipe', 'date +%Y-%m-%d@%H:%M:%S') }}"
         service_status: "success"
         result: "{{role_result}}"   
   set_fact:
      global_log_msgs:   "{{ global_log_msgs + [ role_log ] }}"

      